-- Add Sample Properties for Testing Search Functionality
-- Run this in Supabase SQL Editor after creating missing tables

-- First, let's get a host user ID
DO $$
DECLARE
    host_user_id UUID;
    agent_user_id UUID;
BEGIN
    -- Get the first host user
    SELECT id INTO host_user_id FROM users WHERE is_host = true LIMIT 1;
    
    -- Get the first agent user  
    SELECT id INTO agent_user_id FROM users WHERE is_agent = true LIMIT 1;
    
    -- If no host exists, use the first user and make them a host
    IF host_user_id IS NULL THEN
        SELECT id INTO host_user_id FROM users LIMIT 1;
        UPDATE users SET is_host = true WHERE id = host_user_id;
    END IF;

    -- Insert sample properties
    INSERT INTO properties (
        id,
        host_id,
        title,
        description,
        type,
        emirate,
        city,
        area,
        address,
        latitude,
        longitude,
        bedrooms,
        bathrooms,
        guests,
        base_price,
        security_deposit,
        cleaning_fee,
        amenities,
        house_rules,
        images,
        is_active,
        verification_status,
        is_instant_book,
        created_at,
        updated_at
    ) VALUES 
    (
        gen_random_uuid(),
        host_user_id,
        'Luxury Apartment in Dubai Marina',
        'Stunning 2-bedroom apartment with marina views, fully furnished with modern amenities. Perfect for business travelers and families.',
        'APARTMENT',
        'Dubai',
        'Dubai',
        'Dubai Marina',
        'Marina Walk, Dubai Marina, Dubai',
        25.0657,
        55.1393,
        2,
        2,
        4,
        450.00,
        1000.00,
        150.00,
        'WiFi,Air Conditioning,Kitchen,Washing Machine,TV,Balcony,Gym,Pool,Parking',
        'No smoking,No pets,No parties',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800,https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800,https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        true,
        'VERIFIED',
        true,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        host_user_id,
        'Modern Studio in Downtown Dubai',
        'Stylish studio apartment in the heart of Downtown Dubai, walking distance to Dubai Mall and Burj Khalifa.',
        'STUDIO',
        'Dubai',
        'Dubai',
        'Downtown Dubai',
        'Boulevard Plaza, Downtown Dubai, Dubai',
        25.1972,
        55.2744,
        0,
        1,
        2,
        320.00,
        800.00,
        100.00,
        'WiFi,Air Conditioning,Kitchen,TV,Gym,Pool,Metro Access',
        'No smoking,No pets',
        'https://images.unsplash.com/photo-1560448204-61dc36dc98c8?w=800,https://images.unsplash.com/photo-1560448075-bb485b067938?w=800',
        true,
        'VERIFIED',
        true,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        host_user_id,
        'Spacious Villa in Jumeirah',
        'Beautiful 4-bedroom villa with private pool and garden. Perfect for families and groups.',
        'VILLA',
        'Dubai',
        'Dubai',
        'Jumeirah',
        'Jumeirah Beach Road, Jumeirah, Dubai',
        25.2048,
        55.2708,
        4,
        3,
        8,
        850.00,
        2000.00,
        250.00,
        'WiFi,Air Conditioning,Kitchen,Washing Machine,TV,Private Pool,Garden,Parking,BBQ',
        'No smoking,Pets allowed with deposit,No loud music after 10 PM',
        'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800,https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800,https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
        true,
        'VERIFIED',
        false,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        host_user_id,
        'Cozy Apartment in Abu Dhabi',
        'Comfortable 1-bedroom apartment in Abu Dhabi city center, close to business district.',
        'APARTMENT',
        'Abu Dhabi',
        'Abu Dhabi',
        'Al Markaziyah',
        'Al Markaziyah District, Abu Dhabi',
        24.4539,
        54.3773,
        1,
        1,
        2,
        280.00,
        700.00,
        120.00,
        'WiFi,Air Conditioning,Kitchen,TV,Gym,Pool',
        'No smoking,No pets',
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800,https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        true,
        'VERIFIED',
        true,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        host_user_id,
        'Beachfront Apartment in Sharjah',
        'Stunning beachfront apartment with sea views, perfect for a relaxing getaway.',
        'APARTMENT',
        'Sharjah',
        'Sharjah',
        'Al Majaz',
        'Al Majaz Waterfront, Sharjah',
        25.3373,
        55.3911,
        2,
        2,
        4,
        350.00,
        900.00,
        130.00,
        'WiFi,Air Conditioning,Kitchen,TV,Balcony,Beach Access,Pool',
        'No smoking,No pets,No parties',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800,https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        true,
        'VERIFIED',
        true,
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        host_user_id,
        'Penthouse in Business Bay',
        'Luxurious penthouse with panoramic city views, premium amenities and rooftop terrace.',
        'PENTHOUSE',
        'Dubai',
        'Dubai',
        'Business Bay',
        'Business Bay, Dubai',
        25.1877,
        55.2632,
        3,
        3,
        6,
        750.00,
        1500.00,
        200.00,
        'WiFi,Air Conditioning,Kitchen,Washing Machine,TV,Balcony,Gym,Pool,Parking,Rooftop Terrace',
        'No smoking,No pets,No parties after 11 PM',
        'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800,https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800,https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
        true,
        'VERIFIED',
        false,
        NOW(),
        NOW()
    );

    RAISE NOTICE 'Sample properties added successfully!';
END $$; 