[build]
  base = "."
  command = "npm install && npm run build"
  publish = "build/"

[build.environment]
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 