services:
  # Frontend (React App)
  - type: web
    name: uae-rental-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s build -p $PORT
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: uae-rental-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false

  # Backend (Node.js API)
  - type: web
    name: uae-rental-backend
    env: node
    plan: free
    buildCommand: cd server && npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: uae-rental-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: web
          name: uae-rental-frontend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: uae-rental-db
    databaseName: uae_rental_platform
    user: uae_rental_user
    plan: free 